package com.erp.distribution.desgreenrestkt.domain.model.aux

import com.erp.distribution.desgreenrestkt.data.source.entity.FMaterialGroup3Entity
import com.erp.distribution.desgreenrestkt.data.source.entity.FtSalesdItemsEntity
import java.util.*

class TableJobSchedule1 {
    var iD = 0
    var kapasitasMesin = 0
    var idGroupVarian = 0
    var noUrut = 0 //Baris
    var kolom = 0 //Kolom atau Mesin
    var description_1 = ""
    var fmaterialGroupBean_1 = FMaterialGroup3Entity()
    var group_1 = 0
    var kapasitas_1 = 0
    var terisi_1 = 0
    var prioritas_1 = 0
    var isStartProcess_1 = false
    var isSelesaiProcess_1 = false
    var ftSalesdItems_Entity_1: Set<FtSalesdItemsEntity> = HashSet()
    var description_2 = ""
    var fmaterialGroupBean_2 = FMaterialGroup3Entity()
    var group_2 = 0
    var kapasitas_2 = 0
    var terisi_2 = 0
    var prioritas_2 = 0
    var isStartProcess_2 = false
    var isSelesaiProcess_2 = false
    var ftSalesdItems_Entity_2: Set<FtSalesdItemsEntity> = HashSet()
    var description_3 = ""
    var fmaterialGroupBean_3 = FMaterialGroup3Entity()
    var group_3 = 0
    var kapasitas_3 = 0
    var terisi_3 = 0
    var prioritas_3 = 0
    var isStartProcess_3 = false
    var isSelesaiProcess_3 = false
    var ftSalesdItems_Entity_3: Set<FtSalesdItemsEntity> = HashSet()
    var description_4 = ""
    var fmaterialGroupBean_4 = FMaterialGroup3Entity()
    var group_4 = 0
    var kapasitas_4 = 0
    var terisi_4 = 0
    var prioritas_4 = 0
    var isStartProcess_4 = false
    var isSelesaiProcess_4 = false
    var ftSalesdItems_Entity_4: Set<FtSalesdItemsEntity> = HashSet()
    var description_5 = ""
    var fmaterialGroupBean_5 = FMaterialGroup3Entity()
    var group_5 = 0
    var kapasitas_5 = 0
    var terisi_5 = 0
    var prioritas_5 = 0
    var isStartProcess_5 = false
    var isSelesaiProcess_5 = false
    var ftSalesdItems_Entity_5: Set<FtSalesdItemsEntity> = HashSet()
    var description_6 = ""
    var fmaterialGroupBean_6 = FMaterialGroup3Entity()
    var group_6 = 0
    var kapasitas_6 = 0
    var terisi_6 = 0
    var prioritas_6 = 0
    var isStartProcess_6 = false
    var isSelesaiProcess_6 = false
    var ftSalesdItems_Entity_6: Set<FtSalesdItemsEntity> = HashSet()
    var description_7 = ""
    var fmaterialGroupBean_7 = FMaterialGroup3Entity()
    var group_7 = 0
    var kapasitas_7 = 0
    var terisi_7 = 0
    var prioritas_7 = 0
    var isStartProcess_7 = false
    var isSelesaiProcess_7 = false
    var ftSalesdItems_Entity_7: Set<FtSalesdItemsEntity> = HashSet()
    var description_8 = ""
    var fmaterialGroupBean_8 = FMaterialGroup3Entity()
    var group_8 = 0
    var kapasitas_8 = 0
    var terisi_8 = 0
    var prioritas_8 = 0
    var isStartProcess_8 = false
    var isSelesaiProcess_8 = false
    var ftSalesdItems_Entity_8: Set<FtSalesdItemsEntity> = HashSet()
    var description_9 = ""
    var fmaterialGroupBean_9 = FMaterialGroup3Entity()
    var group_9 = 0
    var kapasitas_9 = 0
    var terisi_9 = 0
    var prioritas_9 = 0
    var isStartProcess_9 = false
    var isSelesaiProcess_9 = false
    var ftSalesdItems_Entity_9: Set<FtSalesdItemsEntity> = HashSet()
    var description_10 = ""
    var fmaterialGroupBean_10 = FMaterialGroup3Entity()
    var group_10 = 0
    var kapasitas_10 = 0
    var terisi_10 = 0
    var prioritas_10 = 0
    var isStartProcess_10 = false
    var isSelesaiProcess_10 = false
    var ftSalesdItems_Entity_10: Set<FtSalesdItemsEntity> = HashSet()
    var description_11 = ""
    var fmaterialGroupBean_11 = FMaterialGroup3Entity()
    var group_11 = 0
    var kapasitas_11 = 0
    var terisi_11 = 0
    var prioritas_11 = 0
    var isStartProcess_11 = false
    var isSelesaiProcess_11 = false
    var ftSalesdItems_Entity_11: Set<FtSalesdItemsEntity> = HashSet()
    var description_12 = ""
    var fmaterialGroupBean_12 = FMaterialGroup3Entity()
    var group_12 = 0
    var kapasitas_12 = 0
    var terisi_12 = 0
    var prioritas_12 = 0
    var isStartProcess_12 = false
    var isSelesaiProcess_12 = false
    var ftSalesdItems_Entity_12: Set<FtSalesdItemsEntity> = HashSet()
    var description_13 = ""
    var fmaterialGroupBean_13 = FMaterialGroup3Entity()
    var group_13 = 0
    var kapasitas_13 = 0
    var terisi_13 = 0
    var prioritas_13 = 0
    var isStartProcess_13 = false
    var isSelesaiProcess_13 = false
    var ftSalesdItems_Entity_13: Set<FtSalesdItemsEntity> = HashSet()
    var description_14 = ""
    var fmaterialGroupBean_14 = FMaterialGroup3Entity()
    var group_14 = 0
    var kapasitas_14 = 0
    var terisi_14 = 0
    var prioritas_14 = 0
    var isStartProcess_14 = false
    var isSelesaiProcess_14 = false
    var ftSalesdItems_Entity_14: Set<FtSalesdItemsEntity> = HashSet()
    var description_15 = ""
    var fmaterialGroupBean_15 = FMaterialGroup3Entity()
    var group_15 = 0
    var kapasitas_15 = 0
    var terisi_15 = 0
    var prioritas_15 = 0
    var isStartProcess_15 = false
    var isSelesaiProcess_15 = false
    var ftSalesdItems_Entity_15: Set<FtSalesdItemsEntity> = HashSet()
    var description_16 = ""
    var fmaterialGroupBean_16 = FMaterialGroup3Entity()
    var group_16 = 0
    var kapasitas_16 = 0
    var terisi_16 = 0
    var prioritas_16 = 0
    var isStartProcess_16 = false
    var isSelesaiProcess_16 = false
    var ftSalesdItems_Entity_16: Set<FtSalesdItemsEntity> = HashSet()
    var description_17 = ""
    var fmaterialGroupBean_17 = FMaterialGroup3Entity()
    var group_17 = 0
    var kapasitas_17 = 0
    var terisi_17 = 0
    var prioritas_17 = 0
    var isStartProcess_17 = false
    var isSelesaiProcess_17 = false
    var ftSalesdItems_Entity_17: Set<FtSalesdItemsEntity> = HashSet()
    var description_18 = ""
    var fmaterialGroupBean_18 = FMaterialGroup3Entity()
    var group_18 = 0
    var kapasitas_18 = 0
    var terisi_18 = 0
    var prioritas_18 = 0
    var isStartProcess_18 = false
    var isSelesaiProcess_18 = false
    var ftSalesdItems_Entity_18: Set<FtSalesdItemsEntity> = HashSet()
    var description_19 = ""
    var fmaterialGroupBean_19 = FMaterialGroup3Entity()
    var group_19 = 0
    var kapasitas_19 = 0
    var terisi_19 = 0
    var prioritas_19 = 0
    var isStartProcess_19 = false
    var isSelesaiProcess_19 = false
    var ftSalesdItems_Entity_19: Set<FtSalesdItemsEntity> = HashSet()
    var description_20 = ""
    var fmaterialGroupBean_20 = FMaterialGroup3Entity()
    var group_20 = 0
    var kapasitas_20 = 0
    var terisi_20 = 0
    var prioritas_20 = 0
    var isStartProcess_20 = false
    var isSelesaiProcess_20 = false
    var ftSalesdItems_Entity_20: Set<FtSalesdItemsEntity> = HashSet()


}